version: "3.9"
services:
  api:
    build: .
    container_name: farmhub_nest_api
    env_file:
      - .env
    environment:
      - DB_HOST=farmhub_db
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules
  db:
    image: postgres:16
    container_name: farmhub_db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  db-test:
    image: postgres:16
    container_name: farmhub_db_tests
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME_TESTS}
    ports:
      - "5433:5432"
volumes:
  pgdata: